//
// Created by tamer on 11/28/2025.
//

#ifndef PUNKVERSEPROJECT_GLOBALS_H
#define PUNKVERSEPROJECT_GLOBALS_H

#define WIN_WIDTH 1280
#define WIN_HEIGHT 720
#define WIN_TITLE "GAME"

#endif //PUNKVERSEPROJECT_GLOBALS_H